# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GymBotUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 110, 303, 125))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_pw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_pw.setObjectName("lineEdit_pw")
        self.gridLayout.addWidget(self.lineEdit_pw, 1, 1, 1, 1)
        self.label_pw = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_pw.setObjectName("label_pw")
        self.gridLayout.addWidget(self.label_pw, 1, 0, 1, 1)
        self.label_un = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_un.setObjectName("label_un")
        self.gridLayout.addWidget(self.label_un, 0, 0, 1, 1)
        self.pushButton_login = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout.addWidget(self.pushButton_login, 2, 1, 1, 1)
        self.lineEdit_un = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_un.setObjectName("lineEdit_un")
        self.gridLayout.addWidget(self.lineEdit_un, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(400, 110, 164, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout.addWidget(self.label_time)
        self.lineEdit_time = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout.addWidget(self.lineEdit_time)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_pw.setText(_translate("MainWindow", "Password:"))
        self.label_un.setText(_translate("MainWindow", "Username:"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label_time.setText(_translate("MainWindow", "Time(24 hour):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
